#!/usr/bin/with-contenv bash

print_vars () {
    if [ -n "${1}" ]; then
	title=" ${1}"
    else
	title=""
    fi
    echo "Environment${title}:"
    echo "    PUID=${PUID}"
    echo "    PGID=${PGID}"
    echo "    TZ=${TZ}"
    for var in "${!MMONIT_@}"; do
	printf '    %s=%s\n' "$var" "${!var}"
    done    
}

print_vars init-mmonit-upgrade

do_upgrade () {
    echo "Upgrading from ${1} to ${2}"
    /config/mmonit-${2}/upgrade/upgrade -d -p /config/mmonit-${1}
    if [ $? -eq 0 ]; then
	echo "Upgrade from ${1} to ${2} succeeded"
	echo ${2} > /config/version
    else
	echo "Upgrade from ${1} to ${2} failed"
	exit $?
    fi
}

# load env file if it exists
if [ -f "/config/env" ]; then
  source /config/env
  print_vars "After sourcing /config/env"
fi

if [ -f /config/.variant ]; then
    old_variant=$(cat /config/.variant)
else
    old_variant=unknown
fi
if [ -x /sbin/apk ]; then
    variant=alpine
else
    variant=linux
fi

# Perform an upgrade if we were running an older version or different variant (alpine vs Ubuntu)
if [ -e /config/version ]; then
    old_version=$(cat /config/version)
    dpkg --compare-versions "${old_version}" "lt" "${MMONIT_VERSION}"; compare=$?
    if [ ${compare} -eq 0 -o "${old_variant}" != "${variant}" ]; then
	if [ -d "/config/mmonit-${old_version}" ]; then
	    mv "/config/mmonit-${old_version}" "/config/mmonit-${old_version}-${old_variant}"
	fi
	rsync -avq /opt/mmonit-${MMONIT_VERSION} /config/ && \
	    do_upgrade "${old_version}-${old_variant}" "${MMONIT_VERSION}" && \
	    echo ${variant} > /config/.variant
    fi
else
    rsync -avq /opt/mmonit-${MMONIT_VERSION} /config/ && \
	echo ${MMONIT_VERSION} > /config/version && \
	echo ${variant} > /config/.variant
fi

echo "init-mmonit-upgrade done"
