#!/usr/bin/with-contenv bash

# Reduce the size of the FD table
ulimit -n ${MMONIT_LIMIT_FD}

# Drop privileges and run M/Monit
s6-setuidgid abc /opt/mmonit-${MMONIT_VERSION}/bin/mmonit -i -r /config

