#!/bin/bash -x

VERSION=$(cat VERSION)

if [ ${DOCKER_TAG} == "latest" ]; then
  docker build . --build-arg mmonit_version=${VERSION} -t ${IMAGE_NAME} -t ${DOCKER_REPO}:${VERSION}
else
  docker build . --build-arg mmonit_version=${DOCKER_TAG} -t ${IMAGE_NAME}
fi
