#!/bin/bash

fail () {
    echo "${*}" >&2
    exit 1
}

TMPFILE=$(mktemp -d -t ${progrname}.XXXXXXXXXX)
trap "test -d ${TMPDIR} && rm -rf ${TMPDIR}" 0 1 2 3 13 15

curl -s -o /dev/null --fail -c ${TMPDIR}/cookie http://127.0.0.1:8080/index.csp || fail "http request failed"

test -f ${TMPDIR}/cookie || fail "no cookie"

test $(wc -l ${TMPDIR}/cookie | cut -d' ' -f 1) -lt 5 && fail "invalid cookie"

exit 0

